### ISSUE TITLE
只是wxml到axml转换吗？如果牵扯到微信的api呢？

### ISSUE THREAD

**Issue by helloqhx** [4013465w/wxmp2antmp#2]
看了代码，大概做法是：用parse5将wxml模版parse成dom树，然后替换成axml标签？这有什么用吗？你有测过真实的例子吗？微信的那么多接口，也没见代码中做转换啊？

**Comment by aOrz** [comment]
请注意看 Readme 中的注意事项 `微信小程序和支付宝小程序的 api 存在差异，建议自行写一套兼容库，暂无 todo 计划` ，本库仅定位于 wxml 的转换，减少一些手工操作
