### ISSUE TITLE
引号会全部转成双引号

### ISSUE THREAD

**Issue by dingtwo** [4013465w/wxmp2antmp#3]
wxml中引号会全部转成双引号

**Comment by wi1dcard** [comment]
Parse 5 的锅，所有属性值都会双引号引用

See: <https://github.com/inikulin/parse5/blob/252819607421a5741cf745bb60c404f023531b0d/packages/parse5/lib/serializer/index.js#L123>

**Comment by wi1dcard** [comment]
然后在[这里](https://github.com/aOrz/wxml2axml/blob/6add2e7c13d76d3213bc3ba07d87a2c9f5afd08f/index.js#L46)被取消转义
